
//TASK LIST

//TODO DECIDE ON DATABASE IMPLEMENTATION
//IS DOCUMENT DATABASE ACCEPTABLE? IF NOT HOW SHOULD I IMPLEMENT RDBMS?

//TODO FIX NOTIFICATIONS SO THAT NEW CHAT ITEM IS ADDED REGARDLESS OF CONVERSATION STARTER

//TODO IMPLEMENT USERNAME CHANGE, CHECK FOR USERNAME EXISTENCE ON THE DB?

//TODO SET UP NOTIFICATION OPTIONS AND IMPLEMENT

//TODO ADD SECURITY OPTIONS
//ADD PASSCODE LOCK FOR APP
//ADD TWO STEP VERIFICATION
//ADD BLOCK USER SETTING AND IMPLEMENT BLOCKED USER LIST
//ADD TOGGLES FOR USER SEARCH OPTIONS
//ADD FUNCTIONALITY FOR USER SEARCHING OPTIONS

//TODO ADD FRIENDS LIST FUNCTIONALITY
//ADD ABILITY TO ADD AND REMOVE FRIENDS FROM FRIEND LIST
//MAKE USER VIEW ONLY DISPLAY ADDED FRIENDS
//ADD FRIEND COUNTER
//MAKE SURE USERS CANNOT SEE USERS THEY HAVE NOD ADDED

//TODO REWORK DESIGN OF FRIENDS LIST SECTION

//TODO BUILD WALLET FUNCTIONALITY

//TODO FIX COLOUR SCHEME ISSUES SO THAT THEY WORK CORRECTLY

//TODO DESIGN OF LOGOS AND BRANDING
